# Generated by Django 3.1.11 on 2021-05-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Pet",
                "verbose_name_plural": "Categorias de Pets",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pet.petcategory",
                verbose_name="Categoria de Pet",
            ),
        ),
    ]
