version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: desafio_ibm_local_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
      - solr
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  solr:
      image: solr:7.7.1
      restart: always
      ports:
         - "8983:8983"
      volumes:
         - ./index/desafio_ibm:/opt/solr/server/solr/desafio_ibm
      environment:
          - SOLR_JAVA_MEM=-Xms512m -Xmx512m
          - SOLR_HEAP=512m

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: desafio_ibm_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: desafio_ibm_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./desafio_ibm:/app/desafio_ibm:z
    ports:
      - "7000:7000"
    command: /start-docs

  adminer:
    image: adminer
    ports:
        - "8080:8080"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: desafio_ibm_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: desafio_ibm_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: desafio_ibm_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
